### ISSUE TITLE
Chatbot respondendo mensagem fora do horário de atendimento, mensagem é enviada junto com a mensagem de ausência.

### ISSUE THREAD

**Issue by danielcostadev** [cleitonme/izing.instalador#1]
Parabéns pelo conteúdo disponibilizado. O chatbot está sendo ativado mesmo fora do horário de atendimento, alguém já conseguiu resolver isso? Ex: Ao invés de enviar apenas a mensagem de ausência, o chatbot também interage.

**Comment by cleitonme** [comment]
isso seria problema na versao izing não instalador terias abrir lá

**Comment by danielcostadev** [comment]
No repositório do izing (no seu fork) não consigo abrir issues.
