### ISSUE TITLE
Importar Contatos

### ISSUE THREAD

**Issue by Elton-Coelho** [cleitonme/izing.instalador#2]
"Internal server error: Error: SequelizeDatabaseError: syntax error at or near \"s\""
ao tentar importar contatos do WhatsApp.

planilha.CSV tbm não está subindo.

![erro importar contatos do WhatsApp](https://github.com/cleitonme/izing.instalador/assets/167256725/4ff20863-751c-46b5-ac5b-a6dfa999acb9)

**Comment by cleitonme** [comment]
testado 2 casos aqui rodando normal pode ser algum problema da sua instalação vps fraca nao carregou banco de dados direito.. teste vps melhor e faça uma instalação nova limpa.. planilha csv sugiro que abra um editor texto para ver ta padrao correto..

nome;numero
Cliente;5511999999999
